### PR TITLE
Updated Environment Variables Cheat Sheet

### PR DESCRIPTION
**Pull request by camalot**
- Added Server Type Sections
- Updated the Server-Types to include the new change on the wording for `CF_API_KEY`

### CODE REVIEW

**Comment by camalot** [comment]
I also noticed, my fork will also publish to the fork `gh-pages`. i have that repo set up correctly now, so it will work. that would be another way to verify the changes that are going in.

**Comment by camalot** [comment]
Welp, i take that back. it runs the main, not PR branch.

**Comment by camalot** [comment]
I modified the `doc-publish.yml` to only run in THIS repo. 

Added a second workflow that will only run in a fork, in branches other than `main` and `gh-pages`

This will make any PR from a fork publish to their `gh-pages` (as long as they have that set up)

need to create an issue to document that process in the docs for contributing 😄

**Review by itzg — COMMENTED** [review]
Just checking, the [Running a server with a CurseForge modpack](https://github.com/itzg/docker-minecraft-server#running-a-server-with-a-curseforge-modpack) section isn't over here yet?

**Comment by camalot** [comment]
> Just checking, the [Running a server with a CurseForge modpack](https://github.com/itzg/docker-minecraft-server#running-a-server-with-a-curseforge-modpack) section isn't over here yet?

https://itzg.github.io/docker-minecraft-docs/java/server-types/#running-a-server-with-a-curseforge-modpack

**Comment by camalot** [comment]
I think the TOC for the server types needs a little cleanup, and i think the `packwiz` section should probably be moved to the server types too.

**Comment by camalot** [comment]
Might even want to break out the "server types" file, so each are in their own... maybe... then add that navigation under the `Server Types` section.

**Comment by itzg** [comment]
Yeah there's too much in "server types" and that explains why I couldn't find the CurseForge info. FYI CurseForge applies to Fabric also. Breaking that out least leaving just server types, and then adjacent mods info in their own page(s).

**Comment by camalot** [comment]
Ok. I know i do lots of commits. i been like that for years. habit i guess...

I split things out, the navigation should be better now too. and easier to find things.

**Comment by itzg** [comment]
Do as many commits as you want 😀 It's a good practice and GitHub let's the PR squash all the commits during merge anyway. So, gives the best of both strategies. 

I was letting the dust settle on this one. Ready for review/merge?

**Comment by camalot** [comment]
yeah, i think this is good for now 😄

**Comment by camalot** [comment]
@itzg i updated the docs here with your latest doc changes for the random RCON password at startup. 

That's great you thought of an easier way to do that, and having it change with every startup.

**Review by itzg — APPROVED** [review]

**Pull request merged**
