### PR TITLE
initial docs setup

### PR DESCRIPTION
**Pull request by camalot**
Adds the starting documentation and images to migrate from the repo README.

### CODE REVIEW

**Comment by itzg** [comment]
Do you know if they (or a GitHub action) have a way to generate a preview of the docs site with the change...in this case the whole thing 😀. Your test site totally serves this purpose but am curious for future PRs.

**Comment by camalot** [comment]
hmmm, i dont think so. might be able to use the test repo in the future. like trigger an action to publish there first, and if it's merged, trigger an approval of the "original PR".

Just a thought...

**Comment by camalot** [comment]
You can, technically, view the file in the branch, which then github will render the markdown. wont be perfect to what mkdocs will render it as, but it's close.

**Comment by itzg** [comment]
> hmmm, i dont think so. might be able to use the test repo in the future. like trigger an action to publish there first, and if it's merged, trigger an approval of the "original PR".
> 
> Just a thought...

That seems like a way to go, but can explore that later, if needed.

**Review by itzg — APPROVED** [review]
Let's kick it off! Thanks for bootstrapping this whole setup.

**Comment by itzg** [comment]
Hmm, there must be something about the repo's github pages setup that I missed since https://itzg.github.io/docker-minecraft-docs isn't being found. Right now I have it like

image

**Comment by camalot** [comment]
I think you have to enable github pages in the repo settings

**Comment by camalot** [comment]
image

this is how i have it set for the other repo

**Comment by itzg** [comment]
Hmm, that "Deploy from a branch" source option is for Github managed pages builds using Jekyll, from what I understand. The image is how I have Github pages enabled for sourcing with Github actions. So, there's something that's not connecting the dots.

**Comment by camalot** [comment]
yeah, but technically this is publishing via the `gh-pages` branch. that is how mkdocs does it behind the scenes, and the github action calls the `mkdocs deploy` which pushes it to `gh-pages` branch.

**Comment by itzg** [comment]
That's odd how they expect it. I can change the configuration to match, but I am uncomfortable with it. `gh-pages` currently contains the rendered documentation, `index.html`, etc. Normally, the "Deploy from branch" references the original Jekyll files.

**Comment by itzg** [comment]
...I just noticed, it is a beta feature. I should provide feedback about it not working as expected:

image

**Comment by camalot** [comment]
> That's odd how they expect it. I can change the configuration to match, but I am uncomfortable with it. `gh-pages` currently contains the rendered documentation, `index.html`, etc. Normally, the "Deploy from branch" references the original Jekyll files.

If you look at the `gh-pages` in the test repo, mkdocs renders everything and generates the files and pushes it to the `gh-pages` branch. the `index.html` there is the "rendered" mkdocs file https://github.com/camalot/mkdocs-test/tree/gh-pages

**Comment by camalot** [comment]
It looks like it also contains a `.nojekyll` file, so that it wont get processed by GH jekyll engine.

**Comment by camalot** [comment]
I am in the process of adding some more env vars to the cheat sheet. Specifically for the different server types.

looks like that change worked, because the docs site is up now!

**Pull request merged**
